# Generated by Django 4.1 on 2022-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('cedula', models.CharField(max_length=11)),
            ],
        ),
    ]
